version: "3.6"

networks:
  discord:
    driver: bridge

services:
  broadcaster:
    image: ghcr.io/chromaminecraft/chroma-broadcaster:main
    container_name: chroma_broadcaster
    environment:
      - FILE_PATH=cron.json
    ports:
      - 8199:8199
    networks:
      - discord
    volumes:
      - ./:/static
